export const Acres = [
  { label: "1 acre", value: 1 },
  { label: "2 acres", value: 2 },
  { label: "3 acres", value: 3 },
  { label: "4 acres", value: 4 },
  { label: "5 acres", value: 5 },
  { label: "6 acres", value: 6 },
  { label: "7 acres", value: 7 },
  { label: "8 acres", value: 8 },
  { label: "9 acres", value: 9 },
  { label: "10 acres", value: 10 },
  { label: "11 acres", value: 11 },
  { label: "12 acres", value: 12 },
  { label: "13 acres", value: 13 },
  { label: "14 acres", value: 14 },
  { label: "15 acres", value: 15 },
  { label: "16 acres", value: 16 },
  { label: "17 acres", value: 17 },
  { label: "18 acres", value: 18 },
  { label: "19 acres", value: 19 },
  { label: "20 acres", value: 20 },
];
