export const Cities = [
  {
    label: "Colombo",
    value: "Colombo",
    subheadings: [
      { label: "Maharagama", value: "Maharagama" },
      { label: "Nugegoda", value: "Nugegoda" },
      { label: "Piliyandala", value: "Piliyandala" },
      { label: "Dehiwala", value: "Dehiwala" },
      { label: "Angoda", value: "Angoda" },
      { label: "Athurugiriya", value: "Athurugiriya" },
      { label: "Avissawella", value: "Avissawella" },
      { label: "Battaramulla", value: "Battaramulla" },
      { label: "Boralasgamuwa", value: "Boralasgamuwa" },
      { label: "Colombo 01", value: "Colombo 01", },
      { label: "Colombo 02", value: "Colombo 02", },
      { label: "Colombo 03", value: "Colombo 03", },
      { label: "Colombo 04", value: "Colombo 04", },
      { label: "Colombo 05", value: "Colombo 05", },
      { label: "Colombo 06", value: "Colombo 06", },
      { label: "Colombo 07", value: "Colombo 07", },
      { label: "Colombo 08", value: "Colombo 08", },
      { label: "Colombo 09", value: "Colombo 09", },
      { label: "Colombo 10", value: "Colombo 10", },
      { label: "Colombo 11", value: "Colombo 11", },
      { label: "Colombo 12", value: "Colombo 12", },
      { label: "Colombo 13", value: "Colombo 13", },
      { label: "Colombo 14", value: "Colombo 14", },
      { label: "Colombo 15", value: "Colombo 15", },
      { label: "Godagama", value: "Godagama" },
      { label: "Hanwella", value: "Hanwella" },
      { label: "Homagama", value: "Homagama" },
      { label: "Kaduwela", value: "Kaduwela" },
      { label: "Kesbawa", value: "Kesbawa" },
      { label: "Kohuwala", value: "Kohuwala" },
      { label: "Kolonnawa", value: "Kolonnawa" },
      { label: "Kottawa", value: "Kottawa" },
      { label: "Kotte", value: "Kotte" },
      { label: "Malabe", value: "Malabe" },
      { label: "Meegoda", value: "Meegoda" },
      { label: "Moratuwa", value: "Moratuwa" },
      { label: "Mount Lavinia", value: "Mount Lavinia" },
      { label: "Nawala", value: "Nawala" },
      { label: "Padukka", value: "Padukka" },
      { label: "Pannipitiya", value: "Pannipitiya" },
      { label: "Rajagiriya", value: "Rajagiriya" },
      { label: "Ratmalana", value: "Ratmalana" },
      { label: "Thalawathugoda", value: "Thalawathugoda" },
      { label: "Wellampitiya", value: "Wellampitiya" },
    ],
  },
  {
    label: "Kandy",
    value: "Kandy",
    subheadings: [
      { label: "Kandy City", value: "Kandy City" },
      { label: "Gampola", value: "Gampola" },
      { label: "Peradeniya", value: "Peradeniya" },
      { label: "Katugastota", value: "Katugastota" },
      { label: "Akurana", value: "Akurana" },
      { label: "Ampitiya", value: "Ampitiya" },
      { label: "Digana", value: "Digana" },
      { label: "Galagedara", value: "Galagedara" },
      { label: "Gelioya", value: "Gelioya" },
      { label: "Kadugannawa", value: "Kadugannawa" },
      { label: "Kundasale", value: "Kundasale" },
      { label: "Madawala Bazaar", value: "Madawala Bazaar" },
      { label: "Menikhinna", value: "Menikhinna" },
      { label: "Nawalapitiya", value: "Nawalapitiya" },
      { label: "Pilimathalawa", value: "Pilimathalawa" },
      { label: "Wattegama", value: "Wattegama" },
    ],
  },
  {
    label: "Galle",
    value: "Galle",
    subheadings: [
      { label: "Galle City", value: "Galle City" },
      { label: "Ambalangoda", value: "Ambalangoda" },
      { label: "Elpitiya", value: "Elpitiya" },
      { label: "Hikkaduwa", value: "Hikkaduwa" },
      { label: "Baddegama", value: "Baddegama" },
      { label: "Ahangama", value: "Ahangama" },
      { label: "Batapola", value: "Batapola" },
      { label: "Karapitiya", value: "Karapitiya" },
    ],
  },
  {
    label: "Ampara",
    value: "Ampara",
    subheadings: [
      { label: "Akkarepattu", value: "Akkarepattu" },
      { label: "Ampara City", value: "Ampara City" },
      { label: "Kalmunei", value: "Kalmunei" },
      { label: "Sainthamaruthe", value: "Sainthamaruthe" },
    ],
  },
  {
    label: "Anuradhapura",
    value: "Anuradhapura",
    subheadings: [
      { label: "Kekirawa", value: "Kekirawa" },
      { label: "Medawachchiya", value: "Medawachchiya" },
      { label: "Tambuttegama", value: "Tambuttegama" },
      { label: "Eppawala", value: "Eppawala" },
      { label: "Galenbindunawewa", value: "Galenbindunawewa" },
      { label: "Galnewa", value: "Galnewa" },
      { label: "Habarana", value: "Habarana" },
      { label: "Mihintale", value: "Mihintale" },
      { label: "Nochchiyagama", value: "Nochchiyagama" },
      { label: "Talawa", value: "Talawa" },
    ],
  },
  {
    label: "Badulla",
    value: "Badulla",
    subheadings: [
      { label: "Badulla City", value: "Badulla City" },
      { label: "Bandarawela", value: "Bandarawela" },
      { label: "Welimada", value: "Welimada" },
      { label: "Mahiyanganaya", value: "Mahiyanganaya" },
      { label: "Hali Ela", value: "Hali Ela" },
      { label: "Ella", value: "Ella" },
      { label: "Haputale", value: "Haputale" },
      { label: "Passara", value: "Passara" },
    ],
  },
  {
    label: "Batticaloa",
    value: "Batticaloa",
    subheadings: [{ label: "Batticaloa City", value: "Batticaloa City" }],
  },
  {
    label: "Gampaha",
    value: "Gampaha",
    subheadings: [
      { label: "Negambo", value: "Negambo" },
      { label: "Kadawatha", value: "Kadawatha" },
      { label: "Kiribathgoda", value: "Kiribathgoda" },
      { label: "Wattala", value: "Wattala" },
      { label: "Delgoda", value: "Delgoda" },
      { label: "Divulapitiya", value: "Divulapitiya" },
      { label: "Ganemulla", value: "Ganemulla" },
      { label: "Ja-Ela", value: "Ja-Ela" },
      { label: "Kandana", value: "Kandana" },
      { label: "Katunayaka", value: "Katunayaka" },
      { label: "Kelaniya", value: "Kelaniya" },
      { label: "Minuwangoda", value: "Minuwangoda" },
      { label: "Mirigama", value: "Mirigama" },
      { label: "Nittambuwa", value: "Nittambuwa" },
      { label: "Ragama", value: "Ragama" },
    ],
  },
  {
    label: "Hambantota",
    value: "Hambantota",
    subheadings: [
      { label: "Tangalla", value: "Tangalla" },
      { label: "Beliatta", value: "Beliatta" },
      { label: "Hambantota City", value: "Hambantota City" },
      { label: "Ambalantota", value: "Ambalantota" },
      { label: "Tissamaharama", value: "Tissamaharama" },
    ],
  },
  {
    label: "Jaffna",
    value: "Jaffna",
    subheadings: [
      { label: "Jaffna City", value: "Jaffna City" },
      { label: "Nallur", value: "Nallur" },
      { label: "Chavakachcheri", value: "Chavakachcheri" },
    ],
  },
  {
    label: "Kalutara",
    value: "Kalutara",
    subheadings: [
      { label: "Panadura", value: "Panadura" },
      { label: "Horana", value: "Horana" },
      { label: "Kalutara", value: "Kalutara" },
      { label: "Bandaragama", value: "Bandaragama" },
      { label: "Matugama", value: "Matugama" },
      { label: "Alutgama", value: "Alutgama" },
      { label: "Beruwala", value: "Beruwala" },
      { label: "Ingiriya", value: "Ingiriya" },
      { label: "Wadduwa", value: "Wadduwa" },
    ],
  },
  {
    label: "Kegalle",
    value: "Kegalle",
    subheadings: [
      { label: "Kegalle City", value: "Kegalle City" },
      { label: "Mawanella", value: "Mawanella" },
      { label: "Warakapola", value: "Warakapola" },
      { label: "Rambukkana", value: "Rambukkana" },
      { label: "Ruwanwella", value: "Ruwanwella" },
      { label: "Dehiowita", value: "Dehiowita" },
      { label: "Galigamuwa", value: "Galigamuwa" },
      { label: "Kitulgala", value: "Kitulgala" },
      { label: "Yatiyantota", value: "Yatiyantota" },
    ],
  },
  {
    label: "Kilinochchi",
    value: "Kilinochchi",
    subheadings: [
      { label: "Kilinochchi City", value: "Kilinochchi City" },
    ],
  },
  {
    label: "Kurunagala",
    value: "Kurunagala",
    subheadings: [
      { label: "Kurunagala City", value: "Kurunagala City" },
      { label: "Kuliyapitiya", value: "Kuliyapitiya" },
      { label: "Mawathagama", value: "Mawathagama" },
      { label: "Narammala", value: "Narammala" },
      { label: "Wariyapola", value: "Wariyapola" },
      { label: "Bingiriya", value: "Bingiriya" },
      { label: "Galgamuwa", value: "Galgamuwa" },
      { label: "Giriulla", value: "Giriulla" },
      { label: "Hettipola", value: "Hettipola" },
      { label: "Ibbagamuwa", value: "Ibbagamuwa" },
      { label: "Nikaweratiya", value: "Nikaweratiya" },
      { label: "Pannala", value: "Pannala" },
      { label: "Polgahawela", value: "Polgahawela" },
    ],
  },
  {
    label: "Mannar",
    value: "Mannar",
    subheadings: [
      { label: "Mannar City", value: "Mannar City" },
    ],
  },
  {
    label: "Matale",
    value: "Matale",
    subheadings: [
      { label: "Matale City", value: "Matale City" },
      { label: "Dambulla", value: "Dambulla" },
      { label: "Galewela", value: "Galewela" },
      { label: "Ukuwela", value: "Ukuwela" },
      { label: "Rattota", value: "Rattota" },
      { label: "Palapathwela", value: "Palapathwela" },
      { label: "Pallepola", value: "Pallepola" },
      { label: "Sigiriya", value: "Sigiriya" },
      { label: "Yatawara", value: "Yatawara" },
    ],
  },
  {
    label: "Matara",
    value: "Matara",
    subheadings: [
      { label: "Matara City", value: "Matara City" },
      { label: "Akuressa", value: "Akuressa" },
      { label: "Weligama", value: "Weligama" },
      { label: "Dikwella", value: "Dikwella" },
      { label: "Hakmana", value: "Hakmana" },
      { label: "Deniyaya", value: "Deniyaya" },
      { label: "Gandara", value: "Gandara" },
      { label: "Kamburugama", value: "Kamburugama" },
      { label: "Kamburupitiya", value: "Kamburupitiya" },
      { label: "Kekanadurra", value: "Kekanadurra" },
    ],
  },
  {
    label: "Monaragala",
    value: "Monaragala",
    subheadings: [
      { label: "Monaragala City", value: "Monaragala City" },
      { label: "Wellawaya", value: "Wellawaya" },
      { label: "Bibile", value: "Bibile" },
      { label: "Buttala", value: "Buttala" },
      { label: "Kataragama", value: "Kataragama" },
    ],
  },
  {
    label: "Mullativu",
    value: "Mullativu",
    subheadings: [
      { label: "Mullative City", value: "Mullative City" },
    ],
  },
  {
    label: "Nuwaraeliya",
    value: "Nuwaraeliya",
    subheadings: [
      { label: "Nuwaraeliya City", value: "Nuwaraeliya City" },
      { label: "Hatton", value: "Hatton" },
      { label: "Ginigathhena", value: "Ginigathhena" },
      { label: "Madulla", value: "Madulla" },
    ],
  },
  {
    label: "Polonnaruwa",
    value: "Polonnaruwa",
    subheadings: [
      { label: "Polonnaruwa City", value: "Polonnaruwa City" },
      { label: "Kaduruwela", value: "Kaduruwela" },
      { label: "Hingurakgoda", value: "Hingurakgoda" },
      { label: "Medirigiriya", value: "Medirigiriya" },
    ],
  },
  {
    label: "Puttalam",
    value: "Puttalam",
    subheadings: [
      { label: "Chilaw", value: "Chilaw" },
      { label: "Puttalam City", value: "Puttalam City" },
      { label: "Wennappuwa", value: "Wennappuwa" },
      { label: "Nattandiya", value: "Nattandiya" },
      { label: "Marawila", value: "Marawila" },
      { label: "Anamaduwa", value: "Anamaduwa" },
      { label: "Dankotuwa", value: "Dankotuwa" },
    ],
  },
  {
    label: "Ratanapura",
    value: "Ratanapura",
    subheadings: [
      { label: "Ratnapura City", value: "Ratnapura City" },
      { label: "Embilipitiya", value: "Embilipitiya" },
      { label: "Balangoda", value: "Balangoda" },
      { label: "Pelmadulla", value: "Pelmadulla" },
      { label: "Eheliyagoda", value: "Eheliyagoda" },
      { label: "Kuruwita", value: "Kuruwita" },
    ],
  },
  {
    label: "Trincomalee",
    value: "Trincomalee",
    subheadings: [
      { label: "Trincomalee City", value: "Trincomalee City" },
      { label: "Kinniya", value: "Kinniya" },
    ],
  },
  {
    label: "Vavuniya",
    value: "Vavuniya",
    subheadings: [{ label: "Vavuniya City", value: "Vavuniya City" }],
  },
];
