export const Perches = [
  { label: "All", value: "All" },
  { label: "1 perch", value: 1 },
  { label: "2 perches", value: 2 },
  { label: "3 perches", value: 3 },
  { label: "4 perches", value: 4 },
  { label: "5 perches", value: 5 },
  { label: "6 perches", value: 6 },
  { label: "7 perches", value: 7 },
  { label: "8 perches", value: 8 },
  { label: "9 perches", value: 9 },
  { label: "10 perches", value: 10 },
  { label: "11 perches", value: 11 },
  { label: "12 perches", value: 12 },
  { label: "13 perches", value: 13 },
  { label: "14 perches", value: 14 },
  { label: "15 perches", value: 15 },
  { label: "16 perches", value: 16 },
  { label: "17 perches", value: 17 },
  { label: "18 perches", value: 18 },
  { label: "19 perches", value: 19 },
  { label: "20 perches", value: 20 },
];
